name: Setup repository
on: [create]
jobs:
  setup:
    name: Reinitialize repository
    runs-on: ubuntu-latest
    steps:
      - name: Render Repo Name
        uses: jayamanikharyono/jinja-action@v0.1
        with:
          data: repo_name=${{ github.event.repository.name }}
          path: test.txt
